### PR TITLE
Add major minor and patch tests

### PR DESCRIPTION
**Pull request by krishandley**
#1 https://github.com/npm/node-semver/blob/master/test/major-minor-patch.js

I wasn't sure if it would be better to put the values through parse or just test the version class, parse doesn't always return a version instance so more tests fail due to nil errors. So I went with version for now.

### CODE REVIEW

**Comment by andrew** [comment]
@krishandley we should totally allow that to work with just version strings as that seems like a likely use case :+1:

**Comment by andrew** [comment]
Also just added you as a collaborator :tada:

**Comment by krishandley** [comment]
:tada: :smile: I've updated the tests to use parse and a fix to make those specs pass.

**Comment by andrew** [comment]
Excellent!

**Pull request merged**
