### PR TITLE
Add support for range and comparators comparison

### LINKED ISSUE #61: Can I compare two ranges with this library?
## Question

Can I check if two `SemanticRange::Range` intersect with this library? What would be the method to call?

### PR DESCRIPTION
**Pull request by rtfpessoa**
* Check if two ranges intersect
* Check if one comparator satisfies a range
* Check if two comparators intersect

Fixes #61

Notes:
I had to change the `Comparator` initializer since it was not working as I expected.
For some reason, in:
```ruby
if comp.is_a?(Comparator)
  return comp if comp.loose == loose
  @comp = comp.value
end
```

The `return comp if comp.loose == loose` was not returning a working Comparator object. Since I am not experienced with ruby I still do not know the internals of the initializer. Maybe you can help me understand this.

Still, my change makes this class use the same logic that exists in `Range` and `Version` by replacing the if with `comp = comp.value if comp.is_a?(Comparator)`. Although it works now I am aware it seems redundant. If you have any insights please let me know.

### CODE REVIEW

**Comment by rtfpessoa** [comment]
fyi, I also did a PR here https://github.com/npm/node-semver/pull/187 and they asked for a couple of changes if you want I can port them here.

**Comment by andrew** [comment]
@rtfpessoa yeah can you port them over here too?

**Comment by rtfpessoa** [comment]
I made all the changes here too, except for the if checking the types. Do you also want those? If yes what would be the exception to throw?

**Comment by andrew** [comment]
Nah that's ok, LGTM 👍

**Pull request merged**
