### PR TITLE
Make options keyword arguments

### PR DESCRIPTION
**Pull request by pustomytnyk**
[node-semver](https://github.com/npm/node-semver) supports "`includePrerelease` flag on the options object to any functions that do range matching" to allow prerelease versions in range (required for checks when we care only about API compatibility like https://github.com/rails/webpacker/issues/2926).

There are already two options as positional arguments, `loose` and `platform`, it would be inconvenient to have all three options as positional ones. So I suggest doing a breaking change: make them keyword arguments and then add `include_prerelease` to existing range functions like this b50588c.

So I'm asking for approval of this approach.

### CODE REVIEW

**Comment by pustomytnyk** [comment]
ping @katzj

**Comment by jsonperl** [comment]
Thanks for this @pustomytnyk. I agree making these keyword arguments is a nicer interface, but I'm also reluctant to make a breaking change like this. I'll do a little more digging/thinking but one initial thought I have is: couldn't we stretch the idea of loose to include pre-releases as well?

**Comment by pustomytnyk** [comment]
> couldn't we stretch the idea of loose to include pre-releases as well?

Well, that would be a breaking change too!

**Comment by jsonperl** [comment]
> Well, that would be a breaking change too!

Point taken 😄

Would you be willing to split this into two PRs? The first would be converting to keyward args, and a second for adding the pre-release bits. I'm thinking we should move to 3.0.0, maybe you can add a note in the README about the changes introduced in that (upcoming) version?

**Comment by jsonperl** [comment]
Thanks @pustomytnyk, can you add a note about the breaking changes in the upcoming 3.0.0 release to the Readme?

**Comment by pustomytnyk** [comment]
@jsonperl feel free to commit more updates to README

**Review by jsonperl — APPROVED** [review]
👍

**Comment by jsonperl** [comment]
Thanks @pustomytnyk, I'll release this as 3.0.0 and then we can do the pre-release update as 3.0.1.

**Comment by jsonperl** [comment]
I'm gonna take the opportunity to swap the default branch to main while I'm here.

**Pull request merged**
